version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: react-cicd-dev

    # Map container port 5173 (Vite) to host port 5173
    ports:
      - '5173:5173'

    # Mount volumes for hot reloading
    volumes:
      - .:/app
      # This prevents node_modules in the container from being overwritten by the host
      - /app/node_modules

    # Set environment to development
    environment:
      - NODE_ENV=development

    # Healthcheck to verify the container is running properly
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:5173']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
